//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace App_Cine_Peli_Plus.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CARTELERA
    {
        public decimal ID_CARTELERA { get; set; }
        public string FECHA { get; set; }
        public string HORARIO { get; set; }
        public decimal ID_CLIENTE { get; set; }
    
        public virtual CLIENTE CLIENTE { get; set; }
    }
}
