//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace App_Cine_Peli_Plus.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class RESERVAS
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public RESERVAS()
        {
            this.PELICULAS = new HashSet<PELICULAS>();
            this.SALA = new HashSet<SALA>();
        }
    
        public decimal ID_RESERVA { get; set; }
        public string TIPO_RESERVA { get; set; }
        public string CANTIDAD_VOLETOS { get; set; }
        public decimal ID_CLIENTE { get; set; }
    
        public virtual CLIENTE CLIENTE { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PELICULAS> PELICULAS { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SALA> SALA { get; set; }
    }
}
